# This file was generated by GoReleaser. DO NOT EDIT.
cask "ajq" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "9c4f30e5457206905f56b159e675a98087631ca8ffbdca713ef99b67799e00b8"
      url "https://github.com/ricardocabral/ajq/releases/download/v#{version}/ajq_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/ricardocabral/ajq"
    end
    on_arm do
      sha256 "c04ec0f40c4ba60f7a3a9e2aa1992332d89f2575fe08e96c716f30f40040ae61"
      url "https://github.com/ricardocabral/ajq/releases/download/v#{version}/ajq_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/ricardocabral/ajq"
    end
  end

  on_linux do
    on_intel do
      sha256 "e09482eb2f05ae73fe00afb7689ed920f4e679645f5aa218ce54b726208f3048"
      url "https://github.com/ricardocabral/ajq/releases/download/v#{version}/ajq_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/ricardocabral/ajq"
    end
    on_arm do
      sha256 "7fc7ba92f5b3e61989e24eea4259c7f4cc30c47be7c732f680d41a90c1d26df2"
      url "https://github.com/ricardocabral/ajq/releases/download/v#{version}/ajq_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/ricardocabral/ajq"
    end
  end

  name "ajq"
  desc "semantic jq for fuzzy JSON filtering and bounded classification"
  homepage "https://github.com/ricardocabral/ajq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ajq"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ajq"]
    end
  end

  # No zap stanza required

end
