# This file was generated by GoReleaser. DO NOT EDIT.
cask "ajq" do
  version "0.0.5"

  on_macos do
    on_intel do
      sha256 "be42be2f68b7fa5410f05e7a1652aa9d65def86087eac5d016e831ae77678bce"
      url "https://github.com/ricardocabral/ajq/releases/download/v#{version}/ajq_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/ricardocabral/ajq"
    end
    on_arm do
      sha256 "0e65f6e304bfc3a80d11bcec307d7eb11709a26d3b9fbdb0853243c1f4c8d6cb"
      url "https://github.com/ricardocabral/ajq/releases/download/v#{version}/ajq_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/ricardocabral/ajq"
    end
  end

  on_linux do
    on_intel do
      sha256 "b6e40d3d67ec07ae6a8092c1d22d84c7fe21892566a45ca12c660845dc24d4e0"
      url "https://github.com/ricardocabral/ajq/releases/download/v#{version}/ajq_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/ricardocabral/ajq"
    end
    on_arm do
      sha256 "67d9bdb22ad81c23f2b4fb33ecd22c9399d4f2d0c2c42958a96e43e71bdaf660"
      url "https://github.com/ricardocabral/ajq/releases/download/v#{version}/ajq_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/ricardocabral/ajq"
    end
  end

  name "ajq"
  desc "semantic jq for fuzzy JSON filtering and bounded classification"
  homepage "https://github.com/ricardocabral/ajq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ajq"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ajq"]
    end
  end

  # No zap stanza required

end
