# This file was generated by GoReleaser. DO NOT EDIT.
cask "ajq" do
  version "0.0.6"

  on_macos do
    on_intel do
      sha256 "8c2b408a9ab2434b688a463acfb6d419887ff86b6902104b204146ff5c7c7e35"
      url "https://github.com/ricardocabral/ajq/releases/download/v#{version}/ajq_#{version}_Darwin_x86_64.tar.gz",
        verified: "github.com/ricardocabral/ajq"
    end
    on_arm do
      sha256 "84afc1118265077b4c18c3e63a910b3ba3dc4636526a5c3f6f5d4d827956bb6c"
      url "https://github.com/ricardocabral/ajq/releases/download/v#{version}/ajq_#{version}_Darwin_arm64.tar.gz",
        verified: "github.com/ricardocabral/ajq"
    end
  end

  on_linux do
    on_intel do
      sha256 "0e419fd0e51d470925c0122f5fdc5f63134245e5ac91a1444430fd2cab8246b3"
      url "https://github.com/ricardocabral/ajq/releases/download/v#{version}/ajq_#{version}_Linux_x86_64.tar.gz",
        verified: "github.com/ricardocabral/ajq"
    end
    on_arm do
      sha256 "31ec16fa2d5b6c180396776a26801be4fd0dc915513e8ba1261ba986ef7dfffd"
      url "https://github.com/ricardocabral/ajq/releases/download/v#{version}/ajq_#{version}_Linux_arm64.tar.gz",
        verified: "github.com/ricardocabral/ajq"
    end
  end

  name "ajq"
  desc "semantic jq for fuzzy JSON filtering and bounded classification"
  homepage "https://github.com/ricardocabral/ajq"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ajq"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ajq"]
    end
  end

  # No zap stanza required

end
