# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Icuvisor < Formula
  desc "MCP server connecting intervals.icu training data to AI assistants."
  homepage "https://icuvisor.app"
  version "0.1.6"
  license "MIT"

  on_macos do
    url "https://github.com/ricardocabral/icuvisor/releases/download/v0.1.6/icuvisor_0.1.6_macos_universal.tar.gz"
    sha256 "efc01e3353b7ace04517eb82411ce890bf5fb71f640464aa8ad15ec0cb1e8348"

    define_method(:install) do
      bin.install "icuvisor"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ricardocabral/icuvisor/releases/download/v0.1.6/icuvisor_0.1.6_linux_amd64.tar.gz"
      sha256 "f906eb1c8a9b0e1c876b97fd8d4a9afc99ebfbfe12cb7591bebb80b22744ee46"
      define_method(:install) do
        bin.install "icuvisor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ricardocabral/icuvisor/releases/download/v0.1.6/icuvisor_0.1.6_linux_arm64.tar.gz"
      sha256 "8c169bb071f6d14855e09681af551518a040b763b86027aecc35d684fb670606"
      define_method(:install) do
        bin.install "icuvisor"
      end
    end
  end

  def caveats
    <<~EOS
      Run `icuvisor setup` once to store your intervals.icu API key in the
      system keychain, then point your MCP client at the `icuvisor` binary.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/icuvisor version")
  end
end
