# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Icuvisor < Formula
  desc "MCP server connecting intervals.icu training data to AI assistants."
  homepage "https://icuvisor.app"
  version "1.7.0"
  license "MIT"

  on_macos do
    url "https://github.com/ricardocabral/icuvisor/releases/download/v1.7.0/icuvisor_1.7.0_macos_universal.tar.gz"
    sha256 "a057f370e89d7975a9dba352b710eabcc66cc5ab1125c7d7bac77b62c4b6f174"

    define_method(:install) do
      bin.install "icuvisor"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ricardocabral/icuvisor/releases/download/v1.7.0/icuvisor_1.7.0_linux_amd64.tar.gz"
      sha256 "9b1999296b208ade92df58530ec5f3f0c61099441fd3a0fc8f771caa27b801f0"
      define_method(:install) do
        bin.install "icuvisor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ricardocabral/icuvisor/releases/download/v1.7.0/icuvisor_1.7.0_linux_arm64.tar.gz"
      sha256 "2afc872e485ff0a4ac947b7d6c49c0f16f03e9fffdb7f08077d09a764208b3e2"
      define_method(:install) do
        bin.install "icuvisor"
      end
    end
  end

  def caveats
    <<~EOS
      Run `icuvisor setup` once to store your intervals.icu API key in the
      system keychain, then point your MCP client at the `icuvisor` binary.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/icuvisor version")
  end
end
