# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Icuvisor < Formula
  desc "MCP server connecting intervals.icu training data to AI assistants."
  homepage "https://icuvisor.app"
  version "1.5.5"
  license "MIT"

  on_macos do
    url "https://github.com/ricardocabral/icuvisor/releases/download/v1.5.5/icuvisor_1.5.5_macos_universal.tar.gz"
    sha256 "f6361a35f1d1eea2ae3db2d5b4c6d86f219d15e7fd88a331ec21daee5b1a6b9a"

    define_method(:install) do
      bin.install "icuvisor"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ricardocabral/icuvisor/releases/download/v1.5.5/icuvisor_1.5.5_linux_amd64.tar.gz"
      sha256 "c37c1ff16f0ad040eca033c98992ad43e3e18283112f6d665ef227c60bb45599"
      define_method(:install) do
        bin.install "icuvisor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ricardocabral/icuvisor/releases/download/v1.5.5/icuvisor_1.5.5_linux_arm64.tar.gz"
      sha256 "04ea01dd7c24f852a5e69d21aa1d7656522a41d2cfa35a5aed9ed48ee1603393"
      define_method(:install) do
        bin.install "icuvisor"
      end
    end
  end

  def caveats
    <<~EOS
      Run `icuvisor setup` once to store your intervals.icu API key in the
      system keychain, then point your MCP client at the `icuvisor` binary.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/icuvisor version")
  end
end
